

class TaskNotFinishedException(Exception):
    pass


class TaskNotFoundException(Exception):
    pass
